#!/bin/bash

# Note: this script requires hub installed: https://hub.github.com/
#  A personal access token should be added to ~/.config/hub
set -e -o pipefail

main() {
    parse_arguments "${@}"

    REPOS_API_PATH="${1}"

    GIT_LFS_SKIP_SMUDGE=1 hub api --paginate --obey-ratelimit -XGET -F per_page=100 "${REPOS_API_PATH}" |
        jq -r '.[].ssh_url' |
        xargs -n1 -P20 git clone --depth=1
}

parse_arguments() {
    while getopts "h" o; do
        case "${o}" in
        h)
            usage
            exit 0
            ;;
        \? | *)
            usage
            exit 1
            ;;
        esac
    done

    shift $((OPTIND - 1))

    if [[ "${#}" -ne 1 ]]; then
        echo "Illegal number of parameters ${0}: got ${#} but expected exactly 1: ${*}" >&2
        usage
        exit 1
    fi
}

usage() {
    cat <<-EOF >&2
		Usage: ${0##*/} [-h] <REPOS_API_PATH>
		
		Clones all repos from the provided API path into the current working directory.
		For example, REPOS_API_PATH can be orgs/<org-name>/repos

		Note: this script requires hub installed: https://hub.github.com/
		  A personal access token should be added to ~/.config/hub

		~/.config/hub file contents between "---"
		---
		github.com:
		- user: <your-user>
		  oauth_token: <your-personal-access-token>
		  protocol: https
		---

		See https://docs.github.com/en/rest/reference/repos#list-organization-repositories
		
		    -h          display this help and exit
	EOF
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "${@}"
fi
