#!/bin/bash
set -e -o pipefail

main() {
    parse_arguments "${@}"

    VENV_NAME=${1:-env}

    python -m venv "${VENV_NAME}"

    # shellcheck disable=SC1091
    source "${VENV_NAME}/bin/activate"

    pip install --upgrade pip

    if [[ -e requirements.txt ]]; then
        pip install -r requirements.txt
    fi

    if [[ -e setup.cfg || -e setup.py || -e pyproject.toml ]]; then
        pip install -e .
    fi
}

parse_arguments() {
    while getopts "h" o; do
        case "${o}" in
        h)
            usage
            exit 0
            ;;
        \? | *)
            usage
            exit 1
            ;;
        esac
    done

    shift $((OPTIND - 1))

    if [[ "${#}" -ne 1 ]]; then
        echo "Illegal number of parameters ${0}: got ${#} but expected exactly 1: ${*}" >&2
        usage
        exit 1
    fi
}

usage() {
    cat <<-EOF >&2
		Usage: ${0##*/} [-h] <ENV_NAME>
		
		Creates a new virtual environment named <ENV_NAME> and installs the dependencies.
		
		    -h          display this help and exit
	EOF
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "${@}"
fi
