#!/bin/bash
set -e

usage() {
    echo "Usage: $0 <env_name>" 1>&2
    exit 1
}

while getopts ":h" o; do
    case "${o}" in
        h | *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [[ "${#}" -ne 1 ]]; then
    echo "Illegal number of parameters ${0}: got ${#} but expected exactly 1: ${*}" >&2
    usage
    return 2
fi

VENV_NAME=${1:-venv}

python -m venv "${VENV_NAME}"

# shellcheck disable=SC1091
source "${VENV_NAME}/bin/activate"

pip install --upgrade pip
pip install -e .
