#!/bin/bash
set -e -o pipefail

main() {
    parse_arguments "${@}"
    printf "# TO-DO:\n-\n\n# Done:\n-\n\n" >"$(date "+%Y-%m-%d")".md
}

parse_arguments() {
    while getopts "h" o; do
        case "${o}" in
        h)
            usage
            exit 0
            ;;
        \? | *)
            usage
            exit 1
            ;;
        esac
    done

    shift $((OPTIND - 1))

    if [[ "${#}" -ne 0 ]]; then
        echo "Illegal number of parameters ${0}: got ${#} but expected exactly 0: ${*}" >&2
        usage
        exit 1
    fi
}

usage() {
    cat <<-EOF >&2
		Usage: ${0##*/} [-h]
		
		Creates a new TO-DO file with today's date into YYYY-MM-DD.md.
		
		    -h          display this help and exit
	EOF
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "${@}"
fi
